//
//  InfoViewController.swift
//  AllAboutFood
//
//  Created by Apiux on 23-09-23.
//

import UIKit

class InfoViewController: UIViewController {

    private struct Types {
        var name: String
        var description: String
        var color: UIColor
    }

    @IBOutlet weak var scroll: UIScrollView!
    @IBOutlet weak var mainStack: UIStackView!
    
    private var types: [Types] = [
        Types(name: "Branded", description: "Label data from national and international Branded Foods generated by industry through a public-private partnership and updated monthly", color: .systemRed),
        Types(name: "Foundation", description: "Data for food components including nutrients derived from analyses, and metadata for a range of single foods and ingredients providing insights into variability. Foundation Foods highlight information on samples and acquisition details.", color: .systemCyan),
        Types(name: "Survey (FNDDS)", description: "Data on 65 food components, including nutrients, and weights for foods and beverages reported in the What We Eat in America dietary survey component of the National Health and Nutrition Examination Survey.", color: .systemIndigo),
        Types(name: "SR Legacy", description: "Data on food components, including nutrients, that are derived from analyses, calculations, and the published literature for a comprehensive list of foods. SR Legacy, released in April 2018, is the final release of this data type and will not be updated.", color: .systemYellow),
        Types(name: "Experimental", description: "Data produced under experimental conditions such as those derived from an experimental design, new analytical methodology and/or are based on innovative sampling procedures for foods used for research purpose only.\n\nExperimental Foods are organized and displayed in four sections: About, Study Design, Results, and Supplemental Information.", color: .systemGray)
    ]

    override func viewDidLoad() {
        super.viewDidLoad()
        let title = UILabel()
        title.font = .systemFont(ofSize: 25)
        title.text = "Colors Information"
        self.mainStack.addArrangedSubview(title)
        for type in types {
            DispatchQueue.main.async {
                let nameLabel = UILabel()
                nameLabel.font = .systemFont(ofSize: 17, weight: .medium)
                nameLabel.text = type.name
                let descriptionLabel = UILabel()
                descriptionLabel.numberOfLines = 0
                descriptionLabel.text = type.description
                let stack = UIStackView()
                stack.axis = .vertical
                stack.spacing = 5
                stack.alignment = .leading
                stack.backgroundColor = type.color.withAlphaComponent(0.1)
                stack.addArrangedSubview(nameLabel)
                stack.addArrangedSubview(descriptionLabel)
                stack.translatesAutoresizingMaskIntoConstraints = false
                stack.isLayoutMarginsRelativeArrangement = true
                stack.layoutMargins = UIEdgeInsets(top: 10, left: 10, bottom: 10, right: 10)

                self.mainStack.addArrangedSubview(stack)
            }
        }
    }
    
    
}
